export default
[{
	"description": "Woman alone",
	"lat": 38.587817,
	"street": "Paseo Dr",
	"location": "Rancho Cordova",
	"time": "4:00AM",
	"date": "6/18/1976",
	"lng": -121.3111954,
	"type": "Attack",
	"id": 1,
	"name": "Attack #1",
	"victimAge": "23",
	"victimOccupation": "Insurance adjuster",
	"recievedCalls": "Yes",
	"weapon":"knife",
	"stolenItems": "$10,fours silver dollers, Winston cigarettes"
}, {
	"description": "Two teenage girls, One attacked",
	"lat": 38.5829737,
	"street": "Marborough Way",
	"location": "Carmichael",
	"time": "2:00AM",
	"date": "7/17/1976",
	"lng": -121.3484644,
	"type": "Attack",
	"id": 2,
	"name": "Attack #2",
	"victimAge": "15",
	"victimOccupation": "Student",
	"recievedCalls": "No",
	"weapon":"knife",
	"stolenItems": "None"
}, {
	"description": "1 Woman, 2 daughters, 15 year old is suspected target,victims escaped. Aborted attack.",
	"lat": 38.5907993,
	"street": "Malaga Way",
	"location": "Rancho Cordova",
	"time": "3:20AM",
	"date": "8/29/1976",
	"lng": -121.3045763,
	"type": "Attack",
	"id": 3,
	"name": "Attack #3",
	"victimAge":"15",
	"victimOccupation": "Student",
	"recievedCalls": "No",
	"weapon":"Gun,Club",
	"stolenItems": "None"
}, {
	"description": "Woman alone",
	"lat": 38.65317150000001,
	"street": "Crestview Drive",
	"location": "Carmichael",
	"time": "11:30PM",
	"date": "9/4/1976",
	"lng": -121.319802,
	"type": "Attack",
	"id": 4,
	"name": "Attack #4",
	"victimAge": "29",
	"victimOccupation": "Clerk(California Dept. of Community Colleges",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "Car"
}, {
	"description": "Woman and Son",
	"lat": 38.6739058,
	"street": "Woodpark Way",
	"location": "Citrus Heights",
	"time": "6:45AM",
	"date": "10/5/1976",
	"lng": -121.3119614,
	"type": "Attack",
	"id": 5,
	"name": "Attack #5",
	"victimAge": "29",
	"victimOccupation": "Air Force Reserve Lieutenant (Travis AFB), Nursing student (California State University Sacramento)",
	"recievedCalls": "Yes",
	"weapon":"Knife",
	"stolenItems": "Earrings, a diamond ring, a bracelet, and other various jewelry"
}, {
	"description": "Woman alone, Neighbor was suspected but ruled out",
	"lat": 38.5909167,
	"street": "El Segundo Dr",
	"location": "Rancho Cordova",
	"time": "4:30AM",
	"date": "10/9/1976",
	"lng": -121.3105864,
	"type": "Attack",
	"id": 6,
	"name": "Attack #6",
	"victimAge": "19",
	"victimOccupation": "Clerk",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": " Three earrings from different sets and a couple of rings that the victim was wearing."
}, {
	"description": "Woman, Son and daughter.Victim later received threatening phone calls in 1991",
	"lat": 38.5864515,
	"street": "Kipling Drive",
	"location": "Carmichael",
	"time": "2:30AM",
	"date": "10/18/1976",
	"lng": -121.3449016,
	"type": "Attack",
	"id": 7,
	"name": "Attack #7",
	"victimAge": "Not available",
	"victimOccupation": "None",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "Wedding rings and other jewelry"
}, {
	"description": "Woman alone. Was returning home from work at time of attack. Aborted attack",
	"lat": 38.5933083,
	"street": "Los Palos",
	"location": "Rancho Cordova",
	"time": "11:00PM",
	"date": "10/18/1976",
	"lng": -121.3108615,
	"type": "Attack",
	"id": 8,
	"name": "Attack #8",
	"victimAge": "19",
	"victimOccupation": "Receptionist(Sacremento Army Depot)",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "Car keys"
}, {
	"description": "Woman alone.Took her to canal. Did not rape(menstruating).",
	"lat": 38.6747646,
	"street": "Greenleaf Drive",
	"location": "Citrus Heights",
	"time": "7:30PM",
	"date": "11/10/1976",
	"lng": -121.3074567,
	"type": "Attack",
	"id": 9,
	"name": "Attack #9",
	"victimAge": "16",
	"victimOccupation": "Student (San Juan High School)",
	"recievedCalls": "Yes",
	"weapon":"Knife",
	"stolenItems": "6 inch serrated knife"
}, {
	"description": "One women",
	"lat": 38.64723,
	"street": "Ladera Way",
	"location": "Fair Oaks",
	"time": "7:20PM",
	"date": "12/18/1976",
	"lng": -121.2987821,
	"type": "Attack",
	"id": 10,
	"name": "Attack #10",
	"victimAge": "15",
	"victimOccupation": "Student",
	"recievedCalls": "Yes",
	"weapon":"Knife",
	"stolenItems": "None"
}, {
	"description": "One woman",
	"lat": 38.5621036,
	"street": "Glenville Circle",
	"location": "Sacramento",
	"time": "11:30PM",
	"date": "1/18/1977",
	"lng": -121.3842878,
	"type": "Attack",
	"id": 11,
	"name": "Attack #11",
	"victimAge": "25",
	"victimOccupation": "Secretary(Sate Capitol",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "Paper money, a digital clock, a pair of keys, an assortment of jewelry, and a cut-out photograph of the victim."
}, {
	"description": "One woman",
	"lat": 38.6685498,
	"street": "Primrose Dr",
	"location": "Citrus Heights",
	"time": "1:00AM",
	"date": "1/24/1977",
	"lng": -121.2765904,
	"type": "Attack",
	"id": 12,
	"name": "Attack #12",
	"victimAge": "25",
	"victimOccupation": "Accountant",
	"recievedCalls": "No",
	"weapon":"Ice pick",
	"stolenItems": "None"
}, {
	"description": "Woman, 7 year old daughter was in house",
	"lat": 38.6546183,
	"street": "Heathcliff Drive",
	"location": "Carmichael",
	"time": "6:50AM",
	"date": "2/7/1977",
	"lng": -121.3183394,
	"type": "Attack",
	"id": 13,
	"name": "Attack #13",
	"victimAge": "30",
	"victimOccupation": "Student(Sacramento State College, Social Science",
	"recievedCalls": "Yes",
	"weapon":"Gun,Knife",
	"stolenItems": "None"
}, {
	"description": "Rodney Miller shot by prowler. Ripon Ct.",
	"lat": 38.5530285,
	"street": "Ripon Ct",
	"location": "Sacramento",
	"time": "11:30PM",
	"date": "2/16/1977",
	"lng": -121.3978895,
	"type": "Attack",
	"id": 14,
	"name": "None",
	"victimAge": "18",
	"victimOccupation": "Athlete",
	"recievedCalls": "No",
	"weapon":"Gun",
	"stolenItems": "None"
}, {
	"description": "Women alone",
	"lat": 38.6232412,
	"street": "Thornwood Drive",
	"location": "Sacramento",
	"time": "4:00AM",
	"date": "3/8/1977",
	"lng": -121.3779157,
	"type": "Attack",
	"id": 15,
	"name": "Attack #14",
	"victimAge": "37",
	"victimOccupation": "Unemployed",
	"recievedCalls": "Yes",
	"weapon":"Butcher Knife",
	"stolenItems": "None"
}, {
	"description": "Teenage girl, This was the only assault where the victim managed to see the suspect's face because he was wearing an open-faced mask",
	"lat": 38.5913525,
	"street": "Benny Way",
	"location": "Rancho Cordova",
	"time": "10:45PM",
	"date": "3/18/1977",
	"lng": -121.3078735,
	"type": "Attack",
	"id": 16,
	"name": "Attack #15",
	"victimAge": "16",
	"victimOccupation": "Fast Food(KFC), Student",
	"recievedCalls": "Yes",
	"weapon":"Ax",
	"stolenItems": "Two rings, the teenager's drivers license, and her sister's school identification"
}, {
	"description": "Couple, This is the first attack in Orangevale, which is a Sacramento County community situated between Interstates 80 and 50",
	"lat": 38.6621708,
	"street": "Richdale Way",
	"location": "Orangevale",
	"time": "3:20AM",
	"date": "4/2/1977",
	"lng": -121.1979307,
	"type": "Attack",
	"id": 17,
	"name": "Attack #16",
	"victimOccupation": "Clerk(Kaiser Pharmacy)",
	"recievedCalls": "No",
	"weapon":"Gun(.45 automatic)",
	"stolenItems": "None"

}, {
	"description": "Woman and her boyfriend",
	"lat": 38.6604713,
	"street": "Cherrelyn Way",
	"location": "Carmichael",
	"time": "2:45AM",
	"date": "4/15/1977",
	"lng": -121.3220267,
	"type": "Attack",
	"id": 18,
	"name": "Attack #17",
	"victimAge": "19",
	"victimOccupation": "Typist",
	"recievedCalls": "Yes",
	"weapon":"Gun,Knife",
	"stolenItems": " Marijuana, a half gram of cocaine, and a pill bottle containing two beans."

}, {
	"description": "Couple",
	"lat": 38.56180579999999,
	"street": "La Riviera Drive",
	"location": "Sacramento",
	"time": "3:00AM",
	"date": "5/3/1977",
	"lng": -121.3870533,
	"type": "Attack",
	"id": 19,
	"name": "Attack #18",
	"victimAge": "N/A",
	"victimOccupation": "Part-time student (Sacramento City College, real estate), Air Force",
	"recievedCalls": "Yes",
	"weapon":"Gun(.45 caliber military automatic)",
	"stolenItems": "Marijuana, a half gram of cocaine, and a pill bottle containing two beans."

}, {
	"description": "Couple",
	"lat": 38.6611126,
	"street": "Winterbrook Drive",
	"location": "Orangevale",
	"time": "12:15AM",
	"date": "5/5/1977",
	"lng": -121.1991945,
	"type": "Attack",
	"id": 20,
	"name": "Attack #19",
	"victimAge": "25",
	"victimOccupation": "Sales Assitant(Stockbroker)",
	"recievedCalls": "No",
	"weapon":"Gun, Knife",
	"stolenItems": "None"
}, {
	"description": "Couple",
	"lat": 38.67492,
	"street": "Merlindale Drive",
	"location": "Citrus Heights",
	"time": "3:45AM",
	"date": "5/14/1977",
	"lng": -121.2783485,
	"type": "Attack",
	"id": 21,
	"name": "Attack #20",
	"victimAge": "N/A",
	"victimOccupation": "Waitress",
	"recievedCalls": "Yes",
	"weapon":"Gun(.45 caliber military automatic), Knife",
	"stolenItems": "Canadian coins, money from Victim's purse, rings from Victim's fingers"
}, {
	"description": "Couple, Two small boys and husband's father",
	"lat": 38.5830128,
	"street": "Sandbar Circle",
	"location": "Carmichael",
	"time": "1:30AM",
	"date": "5/17/1977",
	"lng": -121.3420449,
	"type": "Attack",
	"id": 22,
	"name": "Attack #21",
	"victimAge": "26",
	"victimOccupation": "None",
	"recievedCalls": "Yes",
	"weapon":"Gun,Knife",
	"stolenItems": "None"
}, {
	"description": "Couple and son",
	"lat": 38.4984583,
	"street": "4th Park Way",
	"location": "Sacramento",
	"time": "2:20AM",
	"date": "5/28/1977",
	"lng": -121.445745,
	"type": "Attack",
	"id": 23,
	"name": "Attack #22",
	"victimAge": "N/A",
	"victimOccupation": "None",
	"recievedCalls": "No",
	"weapon":"Gun(.45 caliber military automatic), Knife",
	"stolenItems": "None"
}, {
	"description": "Couple and two children",
	"lat": 37.9957241,
	"street": "Portage Circle South",
	"location": "Stockton",
	"time": "1:30AM",
	"date": "9/6/1977",
	"lng": -121.3591768,
	"type": "Attack",
	"id": 24,
	"name": "Attack #23",
	"victimAge": "27",
	"victimOccupation": "Local business owner",
	"recievedCalls": "Yes(after attack)",
	"weapon":"Gun(.45 caliber military automatic), Knife",
	"stolenItems": "Five silver dollars, wedding and engagement rings, cufflinks, tie pin, man's onyx ring"
}, {
	"description": "Couple",
	"lat": 38.5613186,
	"street": "Tuolumne Drive",
	"location": "Rancho Cordova",
	"time": "1:00AM",
	"date": "10/1/1977",
	"lng": -121.3635279,
	"type": "Attack",
	"id": 25,
	"name": "Attack #24",
	"victimAge": "17",
	"victimOccupation": "Maid (Six Pence Motel - Sacramento)",
	"recievedCalls": "No",
	"weapon":"Gun(revolver), Knife",
	"stolenItems": "None"

}, {
	"description": "Couple and two children",
	"lat": 38.6907953,
	"street": "Gold Run Avenue",
	"location": "Sacramento",
	"time": "3:00AM",
	"date": "10/21/1977",
	"lng": -121.3388581,
	"type": "Attack",
	"id": 26,
	"name": "Attack #25",
	"victimAge": "32",
	"victimOccupation": "None",
	"recievedCalls": "Yes",
	"weapon":"Gun, Knife",
	"stolenItems": "None"

}, {
	"description": "Couple",
	"lat": 38.62930679999999,
	"street": "Woodson Avenue",
	"location": "Sacramento",
	"time": "1:45AM",
	"date": "10/29/1977",
	"lng": -121.3595032,
	"type": "Attack",
	"id": 27,
	"name": "Attack #26",
	"victimAge": "N/A",
	"victimOccupation": "None",
	"recievedCalls": "Yes",
	"weapon":"Gun, Knife",
	"stolenItems": "Wedding rings"
}, {
	"description": "Daughter and Mom",
	"lat": 38.56180579999999,
	"street": "La Riviera Drive",
	"location": "Sacramento",
	"time": "3:30AM",
	"date": "11/10/1977",
	"lng": -121.3870533,
	"type": "Attack",
	"id": 28,
	"name": "Attack #27",
	"victimAge": "13",
	"victimOccupation": "Student(private school)",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "None"
}, {
	"description": "Woman and daughter, EAR removed Victim's clothes but did not sexually assault her. Victim said she heard a van start and leave after EAR had left.",
	"lat": 38.6743765,
	"street": "Brett Dr",
	"location": "Sacramento",
	"time": "11:30PM",
	"date": "12/2/1977",
	"lng": -121.3541561,
	"type": "Attack",
	"id": 29,
	"name": "Attack #28",
	"victimAge": "36",
	"victimOccupation": "None",
	"recievedCalls": "Yes",
	"weapon":"None",
	"stolenItems": "None"

}, {
	"description": "Two young sisters",
	"lat": 38.6490576,
	"street": "Winding Way",
	"location": "Carmichael",
	"time": "11:00PM",
	"date": "1/28/1978",
	"lng": -121.3193011,
	"type": "Attack",
	"id": 30,
	"name": "Attack #29",
	"victimAge": "14,15",
	"victimOccupation": "Students(La Sierra High School)",
	"recievedCalls": "Yes",
	"weapon":"Gun,Knife",
	"stolenItems": "Two small photographs of Victim 1, two homemade earrings from Victim 2 (dimes with holes drilled), money"
}, {
	"description": "Maggiore double murder,Air Force investigators reopened the case in 2014 after receiving a tip 37 years after the murder. EAR was tied to the murder due to laces tied in a specific knot presumably dropped by EAR and found near the scene of the murders. ",
	"lat": 38.5867447,
	"street": "La Algeria Drive",
	"location": "Rancho Cordova",
	"time": "9:15PM",
	"date": "2/2/1978",
	"lng": -121.3179323,
	"type": "Attack",
	"id": 31,
	"name": "None",
	"victimAge": "21,20",
	"victimOccupation": "Air Force Sergeant",
	"recievedCalls": "No",
	"weapon":"Gun",
	"stolenItems": "None"
}, {
	"description": "Couple",
	"lat": 38.0160352,
	"street": "Meadow ave",
	"location": "Stockton",
	"time": "1:05AM",
	"date": "3/18/1978",
	"lng": -121.3358504,
	"type": "Attack",
	"id": 32,
	"name": "Attack #30",
	"victimAge": "N/A",
	"victimOccupation": "None",
	"recievedCalls": "Yes",
	"weapon":"Gun",
	"stolenItems": "Driver's license, $13 cash, $150 in coins, earrings, rings, watch, high school picture of victim"

}, {
	"description": "Single Girl,child was present that she was babysitting",
	"lat": 38.5316825,
	"street": "Pierdmont Ave",
	"location": "Sacramento",
	"time": "9:50PM",
	"date": "4/14/1978",
	"lng": -121.5236465,
	"type": "Attack",
	"id": 33,
	"name": "Attack #31",
	"victimAge": "15",
	"victimOccupation": "Babysitter",
	"recievedCalls": "Yes",
	"weapon":"Gun,Ice pick",
	"stolenItems": "None"
}, {
	"description": "Couple",
	"lat": 37.692017,
	"street": "Fuschia Lane",
	"location": "Modesto",
	"time": "3:00AM",
	"date": "6/5/1978",
	"lng": -120.998068,
	"type": "Attack",
	"id": 34,
	"name": "Attack #32",
	"stolenItems": "None",
	"victimAge": "27",
	"victimOccupation": "None",
	"recievedCalls": "Yes",
	"weapon":"Gun,Knife",
	"stolenItems": "$1500 cash"
}, {
	"description": "Woman Alone",
	"lat": 38.5481497,
	"street": "Wake Forest Dr",//change street address in other file
	"location": "Davis",
	"time": "3:55AM",
	"date": "6/7/1978",
	"lng": -121.7834231,
	"type": "Attack",
	"id": 35,
	"name": "Attack #33",
	"victimAge": "21",
	"victimOccupation": "Student (University of California, Davis)",
	"recievedCalls": "No",
	"weapon":"Screwdriver, Nail File",
	"stolenItems": "None"
}, {
	"description": "Couple",
	"lat": 37.6917507,
	"street": "Grand Prix Dr",//update street address
	"location": "Modesto",
	"time": "1:30AM",
	"date": "6/23/1978",
	"lng": -120.974047,
	"type": "Attack",
	"id": 36,
	"name": "Attack #34",
	"victimAge": "27",
	"victimOccupation": "Modesto City Hospital",
	"recievedCalls": "No",
	"weapon":"Gun,Knife",
	"stolenItems": "Wedding bands, .357 Magnum revolver (from nightstand)"
}, {
	"description": "Couple and three children",
	"lat": 38.5482329,
	"street": "Bucklebury Rd",
	"location": "Davis",
	"time": "3:15AM",
	"date": "6/24/1978",
	"lng": -121.7799347,
	"type": "Attack",
	"id": 37,
	"name": "Attack #35",
	"victimAge": "32",
	"victimOccupation": "Housewife",
	"recievedCalls": "No",
	"weapon":"Gun,Knife,ice pick",
	"stolenItems": "17 rolls of pennies"


}, {
	"description": "Woman and two young sons",
	"lat": 38.5497056,
	"street": "Amador Drive",
	"location": "Davis",
	"time": "2:50AM",
	"date": "7/6/1978",
	"lng": -121.7748113,
	"type": "Attack",
	"id": 38,
	"name": "Attack #36",
	"victimAge": "33",
	"victimOccupation": "Student(Sacremento State College)",
	"recievedCalls": "No",
	"weapon":"Gun,Knife,Screwdriver",
	"stolenItems": "None"
}, {
	"description": "Couple and baby",
	"lat": 37.9435045,
	"street": "Belann Ct",
	"location": "Concord",
	"time": "2:30AM",
	"date": "10/7/1978",
	"lng": -122.0265984,
	"type": "Attack",
	"id": 39,
	"name": "Attack #37",
	"victimAge": "26",
	"victimOccupation": "None",
	"recievedCalls": "No",
	"weapon":"Gun,Knife",
	"stolenItems": "Approximately $4000 in jewelry, dishes, utensils, appliances, camera equipment, and miscellaneous items"
}, {
	"description": "Couple and daughter",
	"lat": 37.9445252,
	"street": "Ryan Court",
	"location": "Concord",
	"time": "4:30AM",
	"date": "10/13/1978",
	"lng": -122.0207784,
	"type": "Attack",
	"id": 40,
	"name": "Attack #38",
	"victimAge": "29",
	"victimOccupation": "Accountant",
	"recievedCalls": "No",
	"weapon":"Gun,Knife",
	"stolenItems": "None"
}, {
	"description": "Attack #39 - Montclair Place",
	"lat": 37.7393183,
	"street": "Montclair Place",
	"location": "San Ramon",
	"time": "2:30AM",
	"date": "10/28/1978",
	"lng": -121.9480848,
	"type": "Attack",
	"id": 41,
	"name": "Attack #39",
	"victimAge": "23",
	"victimOccupation": "Travel agent",
	"recievedCalls": "No",
	"weapon":"Gun",
	"stolenItems": "None"
}, {
	"description": "Woman and baby",
	"lat": 37.3930054,
	"street": "Havenwood Dr",
	"location": "San Jose",
	"time": "3:45AM",
	"date": "11/4/1978",
	"lng": -121.8655947,
	"type": "Attack",
	"id": 42,
	"name": "Attack #40",
	"victimAge": "34",
	"victimOccupation": "None",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "None"
}, {
	"description": "Couple",
	"lat": 37.4027879,
	"street": "Kesey Lane",
	"location": "San Jose",
	"time": "2:00AM",
	"date": "12/2/1978",
	"lng": -121.872515,
	"type": "Attack",
	"id": 43,
	"name": "Attack #41",
	"victimAge": "N/A",
	"victimOccupation": "R.N(Stanford Hospital)",
	"recievedCalls": "No",
	"weapon":"Gun,Knife",
	"stolenItems": "$70, a six-pack of Coors, Gold nugget wedding ring, GE digital clock radio"
}, {
	"description": "Woman alone",
	"lat": 37.8052374,
	"street": "Liberta Ct",
	"location": "Danville",
	"time": "2:00AM",
	"date": "12/9/1978",
	"lng": -121.9848486,
	"type": "Attack",
	"id": 44,
	"name": "Attack #42",
	"victimAge": "32",
	"victimOccupation": "Office Worker(In Danville)",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "Driver's license, ring, antique stickpin, two pendants from a jewelry box"
}, {
	"description": "Woman and two children",
	"lat": 38.6153095,
	"street": "Filmore Lane",
	"location": "Rancho Cordova",
	"time": "5:15AM",
	"date": "3/20/1979",
	"lng": -121.2748523,
	"type": "Attack",
	"id": 45,
	"name": "Attack #43",
	"victimAge": "N/A",
	"victimOccupation": "Secretary (at 2700 block of Cottage Way in Sacramento)",
	"recievedCalls": "Yes",
	"weapon":"Knife",
	"stolenItems": "Jewelry worth $3,000"

}, {
	"description": "Couple",
	"lat": 37.5469656,
	"street": "Honda Way",
	"location": "Fremont",
	"time": "12:20AM",
	"date": "4/4/1979",
	"lng": -121.9445224,
	"type": "Attack",
	"id": 46,
	"name": "Attack #44",
	"victimAge": "27",
	"victimOccupation": "Secretary (in Burlingmae)",
	"recievedCalls": "No",
	"weapon":"Gun,Knife",
	"stolenItems": "$1,600"
}, {
	"description": "Girl,babysitting two kids",
	"lat": 37.9157104,
	"street": "El Divisadero Ave",
	"location": "Walnut Creek",
	"time": "10:30PM",
	"date": "6/2/1979",
	"lng": -122.0323142,
	"type": "Attack",
	"id": 47,
	"name": "Attack #45",
	"victimAge": "17",
	"victimOccupation": "Babysitter",
	"recievedCalls": "Yes",
	"weapon":"Knife",
	"stolenItems": "None"
}, {
	"description": "Couple and 1 child, this is connected to ONS by DNA",
	"lat": 37.8019226,
	"street": "Allegheny Drive",
	"location": "Danville",
	"time": "4:00AM",
	"date": "6/11/1979",
	"lng": -121.9857861,
	"type": "Attack",
	"id": 48,
	"name": "Attack #46",
	"victimAge": "35",
	"victimOccupation": "Housewife",
	"recievedCalls": "No",
	"weapon":"Gun,Knife",
	"stolenItems": "None"
}, {
	"description": "Young girl, Father and 16 year old sister were home",
	"lat": 37.9134998,
	"street": "San Pedro Court",
	"location": "Walnut Creek",
	"time": "4:15AM",
	"date": "6/25/1979",
	"lng": -122.0345353,
	"type": "Attack",
	"id": 49,
	"name": "Attack #47",
	"victimAge": "13",
	"victimOccupation": "Student",
	"recievedCalls": "Yes",
	"weapon":"Knife",
	"stolenItems": "Victim's hairbrush"
}, {
	"description": "Couple,Botched. Victim woke while EAR was putting on mask and help was called.Last known Northern California attack",
	"lat": 37.819154,
	"street": "Thornhill Drive",
	"location": "Danville",
	"time": "4:30AM",
	"date": "7/5/1979",
	"lng": -121.978233,
	"type": "Attack",
	"id": 50,
	"name": "Attack #48",
	"victimAge": "N/A",
	"victimOccupation": "N/A",
	"recievedCalls": "no",
	"weapon":"No",
	"stolenItems": "None"
}, {
	"description": "Couple, Botched attack, ONS #1",
	"lat": 34.4556012,
	"street": "Queen Ann Lane",
	"location": "Goleta",
	"time": "2:00AM",
	"date": "10/1/1979",
	"lng": -119.8144927,
	"type": "Attack",
	"id": 51,
	"name": "ONS Attack #1",
	"victimAge": "N/A",
	"victimOccupation": "Computer programmer",
	"recievedCalls": "No",
	"weapon":"Knife",
	"stolenItems": "None"
}, {
	"description": "Offerman/Manning Murdered, ONS #2",
	"lat": 34.4522488,
	"street": "Avenida Pequena Ave",
	"location": "Goleta",
	"time": "4:00AM",
	"date": "12/30/1979",
	"lng": -119.8116062,
	"type": "Attack",
	"id": 52,
	"name": "ONS Attack #2",
	"victimAge": "44,35",
	"victimOccupation": "Orthopedic surgeon (Offerman), Psychologist (Manning)",
	"recievedCalls": "Yes",
	"weapon":"Gun(.38 caliber revolver)",
	"stolenItems": "None"
}, {
	"description": "Smiths, Murdered",
	"lat": 34.2918461,
	"street": "High Point Dr",
	"location": "Ventura",
	"time": "?",
	"date": "3/13/1980",
	"lng": -119.2013322,
	"type": "Attack",
	"id": 53,
	"name": "ONS Attack #3",
	"victimAge": "43,33",
	"victimOccupation": "Attorney (L. Smith), Interior decorator (C. Smith)",
	"recievedCalls": "No",
	"weapon":"Fire log",
	"stolenItems": "None"
}, {
	"description": "Harringtons, Murdered, Only couple to live in gated community",
	"lat": 33.4772966,
	"street": "Cockleshell Dr",
	"location": "Dana Point",
	"time": "?",
	"date": "8/19/1980",
	"lng": -117.7111636,
	"type": "Attack",
	"id": 54,
	"name": "ONS Attack #4",
	"victimAge": "24,28",
	"victimOccupation": "Medical student (K. Harrington), R.N. (P. Harrington)",
	"recievedCalls": "No",
	"weapon":"Blunt instrument",
	"stolenItems": "None"
}, {
	"description": "Witthuhn",
	"lat": 33.7046628,
	"street": "35 Columbus",
	"location": "Irvine",
	"time": "2:00AM",
	"date": "2/16/1981",
	"lng": -117.7642059,
	"type": "Attack",
	"id": 55,
	"name": "ONS Attack #5",
	"victimAge": "28",
	"victimOccupation": "Student, mortgage broker",
	"recievedCalls": "No",
	"weapon":"Blunt instrument",
	"stolenItems": "None"
}, {
	"description": "Domingo/Sanchez, this case was linked via DNA",
	"lat": 34.4471792,
	"street": "Toltec Way",
	"location": "Goleta",
	"time": "3:30AM",
	"date": "7/27/1981",
	"lng": -119.8142778,
	"type": "Attack",
	"id": 56,
	"name": "ONS Attack #6",
	"victimAge": "35,27",
	"victimOccupation": "Worked with computers",
	"recievedCalls": "No",
	"weapon":"Blunt instrument",
	"stolenItems": "None"
}, {
	"description": "Cruz, youngest known homcide victim",
	"lat": 33.7228641,
	"street": "13 Encina",
	"location": "Irvine",
	"time": "?",
	"date": "5/4/1986",
	"lng": -117.768814,
	"type": "Attack",
	"id": 57,
	"name": "ONS Attack #7",
	"victimAge": "18",
	"victimOccupation": "Cashier(Bullwinkle's pizza)",
	"recievedCalls": "No",
	"weapon":"Blunt instrument",
	"stolenItems": "None"
}]